// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```   
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzKHkk_PVq1WpwP7gEv07C_4CFVho2nI',
    appId: '1:285996212161:web:16792265a24b26a06ed940',
    messagingSenderId: '285996212161',
    projectId: 'field-king-515db',
    authDomain: 'field-king-515db.firebaseapp.com',
    storageBucket: 'field-king-515db.appspot.com',
    measurementId: 'G-7DVM2R00CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbTH4BEEb4ZSMWksFNtVISRlMKA-_b_Y',
    appId: '1:285996212161:android:52c07d8e60672cb36ed940',
    messagingSenderId: '285996212161',
    projectId: 'field-king-515db',
    storageBucket: 'field-king-515db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfx1pzawyO0Et7rrJIU667A-OV9z7xmQ',
    appId: '1:285996212161:ios:745934a26b2bc2156ed940',
    messagingSenderId: '285996212161',
    projectId: 'field-king-515db',
    storageBucket: 'field-king-515db.firebasestorage.app',
    iosBundleId: 'com.example.fieldKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpfx1pzawyO0Et7rrJIU667A-OV9z7xmQ',
    appId: '1:285996212161:ios:04c5dfbd5d8872156ed940',
    messagingSenderId: '285996212161',
    projectId: 'field-king-515db',
    storageBucket: 'field-king-515db.appspot.com',
    iosBundleId: 'com.example.fieldKing.RunnerTests',
  );
}
